#!/usr/bin/env bash

exec 2>&1

set -e

# Make a copy of the distribution for syncing, and inject all the configs.
TEMP_BUILD_PATH="{{ pkg.svc_var_path }}/build"
rm -rf $TEMP_BUILD_PATH
mkdir -p $TEMP_BUILD_PATH

pushd {{ pkg.path }}
cp -R . $TEMP_BUILD_PATH
popd

pushd $TEMP_BUILD_PATH

export DEFAULT_SCENE_SID="{{ cfg.general.default_scene_sid }}"
export BASE_ASSETS_PATH="{{ cfg.general.base_assets_path }}"
export RETICULUM_SERVER="{{ cfg.general.reticulum_server }}"
export POSTGREST_SERVER="{{ cfg.general.postgrest_server }}"
export ITA_SERVER="{{ cfg.general.ita_server }}"
export THUMBNAIL_SERVER="{{ cfg.general.thumbnail_server }}"
export CORS_PROXY_SERVER="{{ cfg.general.cors_proxy_server }}"
export NON_CORS_PROXY_DOMAINS="{{ cfg.general.non_cors_proxy_domains }}"
export SENTRY_DSN="{{ cfg.general.sentry_dsn }}"
export GA_TRACKING_ID="{{ cfg.general.ga_tracking_id }}"
export BUILD_VERSION="{{ pkg.version }}.$(echo "{{ pkg.prefix }}" | cut -d '/' -f 7)"

PATH=$PATH:{{ pkgPathFor "core/git" }}/bin {{ pkgPathFor "core/node10" }}/bin/npm ci --verbose --no-progress
{{ pkgPathFor "core/node10" }}/bin/npm run build

cd admin
PATH=$PATH:{{ pkgPathFor "core/git" }}/bin {{ pkgPathFor "core/node10" }}/bin/npm ci --verbose --no-progress
{{ pkgPathFor "core/node10" }}/bin/npm run build
cp -R dist/* ../dist
cd ..
mkdir -p dist/pages
mv dist/*.html dist/pages
mv dist/hub.service.js dist/pages
mv dist/manifest.webmanifest dist/pages

## need to upload wasm blobs with wasm content type explicitly because, unlike all
## other assets, AWS's built-in MIME type dictionary doesn't know about that one
#
#if [[ "{{ cfg.deploy.type }}" == "s3" ]] ;
#then
#  {{ pkgPathFor "core/aws-cli" }}/bin/aws s3 sync --region {{ cfg.deploy.region }} --acl public-read --cache-control "max-age=31556926" --include "*" --exclude "*.wasm" "$TEMP_BUILD_PATH/dist/assets" "s3://{{ cfg.deploy.target }}/hubs/assets"
#  {{ pkgPathFor "core/aws-cli" }}/bin/aws s3 sync --region {{ cfg.deploy.region }} --acl public-read --cache-control "max-age=31556926" --exclude "*" --include "*.wasm" --content-type "application/wasm" "$TEMP_BUILD_PATH/dist/assets" "s3://{{ cfg.deploy.target }}/hubs/assets"
#  
#  {{ pkgPathFor "core/aws-cli" }}/bin/aws s3 sync --region {{ cfg.deploy.region }} --acl public-read --cache-control "no-cache" --delete "$TEMP_BUILD_PATH/dist/pages" "s3://{{ cfg.deploy.target }}/hubs/pages/latest"
#  {{ pkgPathFor "core/aws-cli" }}/bin/aws s3 sync --region {{ cfg.deploy.region }} --acl public-read --cache-control "no-cache" --delete "$TEMP_BUILD_PATH/dist/pages" "s3://{{ cfg.deploy.target }}/hubs/pages/releases/{{ pkg.version }}.{{ pkg.release }}"
#fi

popd
#exec sleep 999999999999
